export enum GoalCategory {
  EMERGENCY = "EMERGENCY",
  RETIREMENT = "RETIREMENT",
  EDUCATION = "EDUCATION",
  TRAVEL = "TRAVEL",
  LARGE_PURCHASE = "LARGE_PURCHASE",
  INVESTMENT = "INVESTMENT",
  OTHER = "OTHER",
}
