import type {
  RegistrarOperacaoCommand,
  ImportarCarteiraCommand,
  ConfigurarEstrategiaCommand,
  GerenciarAssinaturaCommand,
  SincronizarDadosCommand,
} from "@/application/commands";
import type {
  ObterPatrimonioQuery,
  ConsultarPosicaoQuery,
  ObterProventosQuery,
  CalcularRebalanceamentoQuery,
  GerarRelatorioFiscalQuery,
  ObterHistoricoPatrimonialQuery,
  ConsultarRentabilidadeQuery,
  ExportarDadosQuery,
  ConsultarProgressoMetasQuery,
} from "@/application/queries";
import type {
  PatrimonioDto,
  PosicaoDetalhadaDto,
  OperacaoRegistradaDto,
  ImportacaoRealizadaDto,
  ProventosDto,
  ProventoDto,
  RebalanceamentoDto,
  RelatorioFiscalDto,
  HistoricoPatrimonialDto,
  PontoHistoricoDto,
  RentabilidadeDto,
  ProgressoMetasDto,
  EstrategiaConfiguradaDto,
  AssinaturaAtualizadaDto,
  SincronizacaoRealizadaDto,
  DadosExportadosDto,
} from "@/application/dtos";
import type {
  ApplicationError,
  ValidationError,
  NotFoundError,
  AuthorizationError,
  ConflictError,
  InternalError,
} from "@/application/errors";
import type { IDispatcher } from "@/application/dispatcher";

export type {
  RegistrarOperacaoCommand,
  ImportarCarteiraCommand,
  ConfigurarEstrategiaCommand,
  GerenciarAssinaturaCommand,
  SincronizarDadosCommand,
  ObterPatrimonioQuery,
  ConsultarPosicaoQuery,
  ObterProventosQuery,
  CalcularRebalanceamentoQuery,
  GerarRelatorioFiscalQuery,
  ObterHistoricoPatrimonialQuery,
  ConsultarRentabilidadeQuery,
  ExportarDadosQuery,
  ConsultarProgressoMetasQuery,
  PatrimonioDto,
  PosicaoDetalhadaDto,
  OperacaoRegistradaDto,
  ImportacaoRealizadaDto,
  ProventosDto,
  ProventoDto,
  RebalanceamentoDto,
  RelatorioFiscalDto,
  HistoricoPatrimonialDto,
  PontoHistoricoDto,
  RentabilidadeDto,
  ProgressoMetasDto,
  EstrategiaConfiguradaDto,
  AssinaturaAtualizadaDto,
  SincronizacaoRealizadaDto,
  DadosExportadosDto,
  ApplicationError,
  ValidationError,
  NotFoundError,
  AuthorizationError,
  ConflictError,
  InternalError,
  IDispatcher,
};
