import type { Operation } from "@/shared/types/portfolio";

function monthsAgo(n: number): string {
  const d = new Date();
  d.setMonth(d.getMonth() - n);
  return d.toISOString().split("T")[0];
}

export const DEMO_OPERATIONS: Operation[] = [
  // --- AÇÕES BRASILEIRAS ---
  // PETR4 - primeira compra
  {
    id: "demo-op-01",
    ticker: "PETR4",
    asset_type: "stock",
    currency: "BRL",
    side: "buy",
    quantity: 100,
    price: 36.5,
    fee: 4.9,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(11),
    source: "manual",
    notes: null,
    created_at: monthsAgo(11),
  },
  // VALE3
  {
    id: "demo-op-02",
    ticker: "VALE3",
    asset_type: "stock",
    currency: "BRL",
    side: "buy",
    quantity: 50,
    price: 68.2,
    fee: 3.4,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(10),
    source: "manual",
    notes: null,
    created_at: monthsAgo(10),
  },
  // ITUB4
  {
    id: "demo-op-03",
    ticker: "ITUB4",
    asset_type: "stock",
    currency: "BRL",
    side: "buy",
    quantity: 80,
    price: 28.9,
    fee: 3.1,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(9),
    source: "manual",
    notes: null,
    created_at: monthsAgo(9),
  },
  // WEGE3
  {
    id: "demo-op-12",
    ticker: "WEGE3",
    asset_type: "stock",
    currency: "BRL",
    side: "buy",
    quantity: 40,
    price: 42.3,
    fee: 2.9,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(8),
    source: "manual",
    notes: null,
    created_at: monthsAgo(8),
  },
  // B3SA3
  {
    id: "demo-op-13",
    ticker: "B3SA3",
    asset_type: "stock",
    currency: "BRL",
    side: "buy",
    quantity: 70,
    price: 12.45,
    fee: 2.1,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(7),
    source: "manual",
    notes: null,
    created_at: monthsAgo(7),
  },
  // BBAS3
  {
    id: "demo-op-14",
    ticker: "BBAS3",
    asset_type: "stock",
    currency: "BRL",
    side: "buy",
    quantity: 60,
    price: 25.8,
    fee: 2.5,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(6),
    source: "manual",
    notes: null,
    created_at: monthsAgo(6),
  },
  // BBDC4
  {
    id: "demo-op-11",
    ticker: "BBDC4",
    asset_type: "stock",
    currency: "BRL",
    side: "buy",
    quantity: 60,
    price: 14.75,
    fee: 2.2,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(1),
    source: "manual",
    notes: null,
    created_at: monthsAgo(1),
  },

  // --- VENDAS PARCIAIS ---
  // PETR4 venda parcial
  {
    id: "demo-op-15",
    ticker: "PETR4",
    asset_type: "stock",
    currency: "BRL",
    side: "sell",
    quantity: 20,
    price: 41.2,
    fee: 2.8,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(5),
    source: "manual",
    notes: "Venda parcial para realizar lucro",
    created_at: monthsAgo(5),
  },

  // --- FIIS ---
  // KNCR11
  {
    id: "demo-op-07",
    ticker: "KNCR11",
    asset_type: "fii",
    currency: "BRL",
    side: "buy",
    quantity: 30,
    price: 105.2,
    fee: 2.5,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(5),
    source: "manual",
    notes: null,
    created_at: monthsAgo(5),
  },
  // HGLG11
  {
    id: "demo-op-08",
    ticker: "HGLG11",
    asset_type: "fii",
    currency: "BRL",
    side: "buy",
    quantity: 20,
    price: 165.4,
    fee: 2.8,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(4),
    source: "manual",
    notes: null,
    created_at: monthsAgo(4),
  },
  // XPML11
  {
    id: "demo-op-16",
    ticker: "XPML11",
    asset_type: "fii",
    currency: "BRL",
    side: "buy",
    quantity: 25,
    price: 112.8,
    fee: 2.3,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(3),
    source: "manual",
    notes: null,
    created_at: monthsAgo(3),
  },
  // KNRI11
  {
    id: "demo-op-17",
    ticker: "KNRI11",
    asset_type: "fii",
    currency: "BRL",
    side: "buy",
    quantity: 15,
    price: 145.6,
    fee: 2.6,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(2),
    source: "manual",
    notes: null,
    created_at: monthsAgo(2),
  },

  // --- DIVIDENDOS AÇÕES ---
  // PETR4 dividendos
  {
    id: "demo-op-04",
    ticker: "PETR4",
    asset_type: "stock",
    currency: "BRL",
    side: "dividend",
    quantity: 100,
    price: 1.45,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(8),
    source: "sync",
    notes: null,
    created_at: monthsAgo(8),
  },
  {
    id: "demo-op-18",
    ticker: "PETR4",
    asset_type: "stock",
    currency: "BRL",
    side: "dividend",
    quantity: 80,
    price: 1.32,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(4),
    source: "sync",
    notes: null,
    created_at: monthsAgo(4),
  },
  // VALE3 dividendos
  {
    id: "demo-op-05",
    ticker: "VALE3",
    asset_type: "stock",
    currency: "BRL",
    side: "dividend",
    quantity: 50,
    price: 2.1,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(7),
    source: "sync",
    notes: null,
    created_at: monthsAgo(7),
  },
  {
    id: "demo-op-19",
    ticker: "VALE3",
    asset_type: "stock",
    currency: "BRL",
    side: "dividend",
    quantity: 50,
    price: 1.85,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(3),
    source: "sync",
    notes: null,
    created_at: monthsAgo(3),
  },
  // ITUB4 JCP
  {
    id: "demo-op-06",
    ticker: "ITUB4",
    asset_type: "stock",
    currency: "BRL",
    side: "dividend",
    quantity: 80,
    price: 0.85,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "jcp", auto_sync: true },
    traded_at: monthsAgo(6),
    source: "sync",
    notes: null,
    created_at: monthsAgo(6),
  },
  // WEGE3 dividendos
  {
    id: "demo-op-20",
    ticker: "WEGE3",
    asset_type: "stock",
    currency: "BRL",
    side: "dividend",
    quantity: 40,
    price: 0.62,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(5),
    source: "sync",
    notes: null,
    created_at: monthsAgo(5),
  },

  // --- DIVIDENDOS FIIS (mensais) ---
  // KNCR11 dividendos
  {
    id: "demo-op-09",
    ticker: "KNCR11",
    asset_type: "fii",
    currency: "BRL",
    side: "dividend",
    quantity: 30,
    price: 0.95,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(3),
    source: "sync",
    notes: null,
    created_at: monthsAgo(3),
  },
  {
    id: "demo-op-21",
    ticker: "KNCR11",
    asset_type: "fii",
    currency: "BRL",
    side: "dividend",
    quantity: 30,
    price: 0.92,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(2),
    source: "sync",
    notes: null,
    created_at: monthsAgo(2),
  },
  {
    id: "demo-op-22",
    ticker: "KNCR11",
    asset_type: "fii",
    currency: "BRL",
    side: "dividend",
    quantity: 30,
    price: 0.97,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(1),
    source: "sync",
    notes: null,
    created_at: monthsAgo(1),
  },
  // HGLG11 dividendos
  {
    id: "demo-op-10",
    ticker: "HGLG11",
    asset_type: "fii",
    currency: "BRL",
    side: "dividend",
    quantity: 20,
    price: 1.2,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(2),
    source: "sync",
    notes: null,
    created_at: monthsAgo(2),
  },
  {
    id: "demo-op-23",
    ticker: "HGLG11",
    asset_type: "fii",
    currency: "BRL",
    side: "dividend",
    quantity: 20,
    price: 1.15,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(0),
    source: "sync",
    notes: null,
    created_at: monthsAgo(0),
  },
  // XPML11 dividendos
  {
    id: "demo-op-24",
    ticker: "XPML11",
    asset_type: "fii",
    currency: "BRL",
    side: "dividend",
    quantity: 25,
    price: 0.88,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(1),
    source: "sync",
    notes: null,
    created_at: monthsAgo(1),
  },
  {
    id: "demo-op-25",
    ticker: "XPML11",
    asset_type: "fii",
    currency: "BRL",
    side: "dividend",
    quantity: 25,
    price: 0.91,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(0),
    source: "sync",
    notes: null,
    created_at: monthsAgo(0),
  },
  // KNRI11 dividendo
  {
    id: "demo-op-26",
    ticker: "KNRI11",
    asset_type: "fii",
    currency: "BRL",
    side: "dividend",
    quantity: 15,
    price: 1.05,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(0),
    source: "sync",
    notes: null,
    created_at: monthsAgo(0),
  },
];
