import type { Operation } from "@/lib/portfolio/models";

function monthsAgo(n: number): string {
  const d = new Date();
  d.setMonth(d.getMonth() - n);
  return d.toISOString().split("T")[0];
}

export const DEMO_OPERATIONS: Operation[] = [
  {
    id: "demo-op-01",
    ticker: "PETR4",
    asset_type: "stock",
    currency: "BRL",
    side: "buy",
    quantity: 100,
    price: 36.5,
    fee: 4.9,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(11),
    source: "manual",
    notes: null,
    created_at: monthsAgo(11),
  },
  {
    id: "demo-op-02",
    ticker: "VALE3",
    asset_type: "stock",
    currency: "BRL",
    side: "buy",
    quantity: 50,
    price: 68.2,
    fee: 3.4,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(10),
    source: "manual",
    notes: null,
    created_at: monthsAgo(10),
  },
  {
    id: "demo-op-03",
    ticker: "ITUB4",
    asset_type: "stock",
    currency: "BRL",
    side: "buy",
    quantity: 80,
    price: 28.9,
    fee: 3.1,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(9),
    source: "manual",
    notes: null,
    created_at: monthsAgo(9),
  },
  {
    id: "demo-op-04",
    ticker: "PETR4",
    asset_type: "stock",
    currency: "BRL",
    side: "dividend",
    quantity: 100,
    price: 1.45,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(8),
    source: "sync",
    notes: null,
    created_at: monthsAgo(8),
  },
  {
    id: "demo-op-05",
    ticker: "VALE3",
    asset_type: "stock",
    currency: "BRL",
    side: "dividend",
    quantity: 50,
    price: 2.1,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(7),
    source: "sync",
    notes: null,
    created_at: monthsAgo(7),
  },
  {
    id: "demo-op-06",
    ticker: "ITUB4",
    asset_type: "stock",
    currency: "BRL",
    side: "dividend",
    quantity: 80,
    price: 0.85,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "jcp", auto_sync: true },
    traded_at: monthsAgo(6),
    source: "sync",
    notes: null,
    created_at: monthsAgo(6),
  },
  {
    id: "demo-op-07",
    ticker: "KNCR11",
    asset_type: "fii",
    currency: "BRL",
    side: "buy",
    quantity: 30,
    price: 105.2,
    fee: 2.5,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(5),
    source: "manual",
    notes: null,
    created_at: monthsAgo(5),
  },
  {
    id: "demo-op-08",
    ticker: "HGLG11",
    asset_type: "fii",
    currency: "BRL",
    side: "buy",
    quantity: 20,
    price: 165.4,
    fee: 2.8,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(4),
    source: "manual",
    notes: null,
    created_at: monthsAgo(4),
  },
  {
    id: "demo-op-09",
    ticker: "KNCR11",
    asset_type: "fii",
    currency: "BRL",
    side: "dividend",
    quantity: 30,
    price: 0.95,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(3),
    source: "sync",
    notes: null,
    created_at: monthsAgo(3),
  },
  {
    id: "demo-op-10",
    ticker: "HGLG11",
    asset_type: "fii",
    currency: "BRL",
    side: "dividend",
    quantity: 20,
    price: 1.2,
    fee: 0,
    irrf: 0,
    other_costs: 0,
    metadata: { tipo_provento: "dividendo", auto_sync: true },
    traded_at: monthsAgo(2),
    source: "sync",
    notes: null,
    created_at: monthsAgo(2),
  },
  {
    id: "demo-op-11",
    ticker: "BBDC4",
    asset_type: "stock",
    currency: "BRL",
    side: "buy",
    quantity: 60,
    price: 14.75,
    fee: 2.2,
    irrf: 0,
    other_costs: 0,
    metadata: null,
    traded_at: monthsAgo(1),
    source: "manual",
    notes: null,
    created_at: monthsAgo(1),
  },
];
