/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetoresRouteImport } from './routes/setores'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as FiisRouteImport } from './routes/fiis'
import { Route as DividendosRouteImport } from './routes/dividendos'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as CarteirasRecomendadasRouteImport } from './routes/carteiras-recomendadas'
import { Route as CalculadorasRouteImport } from './routes/calculadoras'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchlistIndexRouteImport } from './routes/watchlist.index'
import { Route as FiiTickerRouteImport } from './routes/fii.$ticker'
import { Route as AtivoTickerRouteImport } from './routes/ativo.$ticker'
import { Route as AuthenticatedProvisionadorRouteImport } from './routes/_authenticated/provisionador'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as AuthenticatedIrpfIndexRouteImport } from './routes/_authenticated/irpf.index'
import { Route as AuthenticatedCarteiraIndexRouteImport } from './routes/_authenticated/carteira.index'
import { Route as AuthenticatedCarteiraOperacoesRouteImport } from './routes/_authenticated/carteira.operacoes'
import { Route as AuthenticatedCarteiraCoberturaRouteImport } from './routes/_authenticated/carteira.cobertura'

const SetoresRoute = SetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const FiisRoute = FiisRouteImport.update({
  id: '/fiis',
  path: '/fiis',
  getParentRoute: () => rootRouteImport,
} as any)
const DividendosRoute = DividendosRouteImport.update({
  id: '/dividendos',
  path: '/dividendos',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteirasRecomendadasRoute = CarteirasRecomendadasRouteImport.update({
  id: '/carteiras-recomendadas',
  path: '/carteiras-recomendadas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasRoute = CalculadorasRouteImport.update({
  id: '/calculadoras',
  path: '/calculadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistIndexRoute = WatchlistIndexRouteImport.update({
  id: '/watchlist/',
  path: '/watchlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const FiiTickerRoute = FiiTickerRouteImport.update({
  id: '/fii/$ticker',
  path: '/fii/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivoTickerRoute = AtivoTickerRouteImport.update({
  id: '/ativo/$ticker',
  path: '/ativo/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProvisionadorRoute = AuthenticatedProvisionadorRouteImport.update({
  id: '/_authenticated/provisionador',
  path: '/provisionador',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/_authenticated/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedIrpfIndexRoute = AuthenticatedIrpfIndexRouteImport.update({
  id: '/irpf/',
  path: '/irpf/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteiraIndexRoute =
  AuthenticatedCarteiraIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraOperacoesRoute =
  AuthenticatedCarteiraOperacoesRouteImport.update({
    id: '/operacoes',
    path: '/operacoes',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraCoberturaRoute =
  AuthenticatedCarteiraCoberturaRouteImport.update({
    id: '/cobertura',
    path: '/cobertura',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculadoras': typeof CalculadorasRoute
  '/carteiras-recomendadas': typeof CarteirasRecomendadasRoute
  '/comparar': typeof CompararRoute
  '/dividendos': typeof DividendosRoute
  '/fiis': typeof FiisRoute
  '/noticias': typeof NoticiasRoute
  '/rankings': typeof RankingsRoute
  '/setores': typeof SetoresRoute
  '/carteira': typeof AuthenticatedCarteiraRouteWithChildren
  '/ativo/$ticker': typeof AtivoTickerRoute
  '/fii/$ticker': typeof FiiTickerRoute
  '/watchlist/': typeof WatchlistIndexRoute
  '/carteira/operacoes': typeof AuthenticatedCarteiraOperacoesRoute
  '/carteira/cobertura': typeof AuthenticatedCarteiraCoberturaRoute
  '/carteira/': typeof AuthenticatedCarteiraIndexRoute
  '/irpf/': typeof AuthenticatedIrpfIndexRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/provisionador': typeof AuthenticatedProvisionadorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculadoras': typeof CalculadorasRoute
  '/carteiras-recomendadas': typeof CarteirasRecomendadasRoute
  '/comparar': typeof CompararRoute
  '/dividendos': typeof DividendosRoute
  '/fiis': typeof FiisRoute
  '/noticias': typeof NoticiasRoute
  '/rankings': typeof RankingsRoute
  '/setores': typeof SetoresRoute
  '/ativo/$ticker': typeof AtivoTickerRoute
  '/fii/$ticker': typeof FiiTickerRoute
  '/watchlist': typeof WatchlistIndexRoute
  '/carteira/operacoes': typeof AuthenticatedCarteiraOperacoesRoute
  '/carteira/cobertura': typeof AuthenticatedCarteiraCoberturaRoute
  '/carteira': typeof AuthenticatedCarteiraIndexRoute
  '/irpf': typeof AuthenticatedIrpfIndexRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/provisionador': typeof AuthenticatedProvisionadorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/calculadoras': typeof CalculadorasRoute
  '/carteiras-recomendadas': typeof CarteirasRecomendadasRoute
  '/comparar': typeof CompararRoute
  '/dividendos': typeof DividendosRoute
  '/fiis': typeof FiisRoute
  '/noticias': typeof NoticiasRoute
  '/rankings': typeof RankingsRoute
  '/setores': typeof SetoresRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRouteWithChildren
  '/ativo/$ticker': typeof AtivoTickerRoute
  '/fii/$ticker': typeof FiiTickerRoute
  '/watchlist/': typeof WatchlistIndexRoute
  '/_authenticated/carteira/operacoes': typeof AuthenticatedCarteiraOperacoesRoute
  '/_authenticated/carteira/cobertura': typeof AuthenticatedCarteiraCoberturaRoute
  '/_authenticated/carteira/': typeof AuthenticatedCarteiraIndexRoute
  '/_authenticated/irpf/': typeof AuthenticatedIrpfIndexRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/provisionador': typeof AuthenticatedProvisionadorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calculadoras'
    | '/carteiras-recomendadas'
    | '/comparar'
    | '/dividendos'
    | '/fiis'
    | '/noticias'
    | '/rankings'
    | '/setores'
    | '/carteira'
    | '/ativo/$ticker'
    | '/fii/$ticker'
    | '/watchlist/'
    | '/carteira/operacoes'
    | '/carteira/cobertura'
    | '/carteira/'
    | '/irpf/'
    | '/metas'
    | '/provisionador'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculadoras'
    | '/carteiras-recomendadas'
    | '/comparar'
    | '/dividendos'
    | '/fiis'
    | '/noticias'
    | '/rankings'
    | '/setores'
    | '/ativo/$ticker'
    | '/fii/$ticker'
    | '/watchlist'
    | '/carteira/operacoes'
    | '/carteira/cobertura'
    | '/carteira'
    | '/irpf'
    | '/metas'
    | '/provisionador'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/calculadoras'
    | '/carteiras-recomendadas'
    | '/comparar'
    | '/dividendos'
    | '/fiis'
    | '/noticias'
    | '/rankings'
    | '/setores'
    | '/_authenticated/carteira'
    | '/ativo/$ticker'
    | '/fii/$ticker'
    | '/watchlist/'
    | '/_authenticated/carteira/operacoes'
    | '/_authenticated/carteira/cobertura'
    | '/_authenticated/carteira/'
    | '/_authenticated/irpf/'
    | '/_authenticated/metas'
    | '/_authenticated/provisionador'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalculadorasRoute: typeof CalculadorasRoute
  CarteirasRecomendadasRoute: typeof CarteirasRecomendadasRoute
  CompararRoute: typeof CompararRoute
  DividendosRoute: typeof DividendosRoute
  FiisRoute: typeof FiisRoute
  NoticiasRoute: typeof NoticiasRoute
  RankingsRoute: typeof RankingsRoute
  SetoresRoute: typeof SetoresRoute
  AtivoTickerRoute: typeof AtivoTickerRoute
  FiiTickerRoute: typeof FiiTickerRoute
  WatchlistIndexRoute: typeof WatchlistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setores': {
      id: '/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof SetoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiis': {
      id: '/fiis'
      path: '/fiis'
      fullPath: '/fiis'
      preLoaderRoute: typeof FiisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividendos': {
      id: '/dividendos'
      path: '/dividendos'
      fullPath: '/dividendos'
      preLoaderRoute: typeof DividendosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteiras-recomendadas': {
      id: '/carteiras-recomendadas'
      path: '/carteiras-recomendadas'
      fullPath: '/carteiras-recomendadas'
      preLoaderRoute: typeof CarteirasRecomendadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras': {
      id: '/calculadoras'
      path: '/calculadoras'
      fullPath: '/calculadoras'
      preLoaderRoute: typeof CalculadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist/': {
      id: '/watchlist/'
      path: '/watchlist'
      fullPath: '/watchlist/'
      preLoaderRoute: typeof WatchlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fii/$ticker': {
      id: '/fii/$ticker'
      path: '/fii/$ticker'
      fullPath: '/fii/$ticker'
      preLoaderRoute: typeof FiiTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativo/$ticker': {
      id: '/ativo/$ticker'
      path: '/ativo/$ticker'
      fullPath: '/ativo/$ticker'
      preLoaderRoute: typeof AtivoTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/provisionador': {
      id: '/_authenticated/provisionador'
      path: '/provisionador'
      fullPath: '/provisionador'
      preLoaderRoute: typeof AuthenticatedProvisionadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/irpf/': {
      id: '/_authenticated/irpf/'
      path: '/irpf'
      fullPath: '/irpf/'
      preLoaderRoute: typeof AuthenticatedIrpfIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira/': {
      id: '/_authenticated/carteira/'
      path: '/'
      fullPath: '/carteira/'
      preLoaderRoute: typeof AuthenticatedCarteiraIndexRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/operacoes': {
      id: '/_authenticated/carteira/operacoes'
      path: '/operacoes'
      fullPath: '/carteira/operacoes'
      preLoaderRoute: typeof AuthenticatedCarteiraOperacoesRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/cobertura': {
      id: '/_authenticated/carteira/cobertura'
      path: '/cobertura'
      fullPath: '/carteira/cobertura'
      preLoaderRoute: typeof AuthenticatedCarteiraCoberturaRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
  }
}

interface AuthenticatedCarteiraRouteChildren {
  AuthenticatedCarteiraOperacoesRoute: typeof AuthenticatedCarteiraOperacoesRoute
  AuthenticatedCarteiraCoberturaRoute: typeof AuthenticatedCarteiraCoberturaRoute
  AuthenticatedCarteiraIndexRoute: typeof AuthenticatedCarteiraIndexRoute
}

const AuthenticatedCarteiraRouteChildren: AuthenticatedCarteiraRouteChildren = {
  AuthenticatedCarteiraOperacoesRoute: AuthenticatedCarteiraOperacoesRoute,
  AuthenticatedCarteiraCoberturaRoute: AuthenticatedCarteiraCoberturaRoute,
  AuthenticatedCarteiraIndexRoute: AuthenticatedCarteiraIndexRoute,
}

const AuthenticatedCarteiraRouteWithChildren =
  AuthenticatedCarteiraRoute._addFileChildren(
    AuthenticatedCarteiraRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRouteWithChildren
  AuthenticatedIrpfIndexRoute: typeof AuthenticatedIrpfIndexRoute
  AuthenticatedProvisionadorRoute: typeof AuthenticatedProvisionadorRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRouteWithChildren,
  AuthenticatedIrpfIndexRoute: AuthenticatedIrpfIndexRoute,
  AuthenticatedProvisionadorRoute: AuthenticatedProvisionadorRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CalculadorasRoute: CalculadorasRoute,
  CarteirasRecomendadasRoute: CarteirasRecomendadasRoute,
  CompararRoute: CompararRoute,
  DividendosRoute: DividendosRoute,
  FiisRoute: FiisRoute,
  MetasRoute: MetasRoute,
  NoticiasRoute: NoticiasRoute,
  ProvisionadorRoute: ProvisionadorRoute,
  RankingsRoute: RankingsRoute,
  SetoresRoute: SetoresRoute,
  AtivoTickerRoute: AtivoTickerRoute,
  FiiTickerRoute: FiiTickerRoute,
  WatchlistIndexRoute: WatchlistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
