/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SetoresRouteImport } from './routes/setores'
import { Route as RankingsRouteImport } from './routes/rankings'
import { Route as NoticiasRouteImport } from './routes/noticias'
import { Route as FiisRouteImport } from './routes/fiis'
import { Route as DividendosRouteImport } from './routes/dividendos'
import { Route as CompararRouteImport } from './routes/comparar'
import { Route as CarteirasRecomendadasRouteImport } from './routes/carteiras-recomendadas'
import { Route as CalculadorasRouteImport } from './routes/calculadoras'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WatchlistIndexRouteImport } from './routes/watchlist.index'
import { Route as FiiTickerRouteImport } from './routes/fii.$ticker'
import { Route as AtivoTickerRouteImport } from './routes/ativo.$ticker'
import { Route as AuthenticatedProvisionadorRouteImport } from './routes/_authenticated/provisionador'
import { Route as AuthenticatedMetasRouteImport } from './routes/_authenticated/metas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCarteiraRouteImport } from './routes/_authenticated/carteira'
import { Route as _authRegisterRouteImport } from './routes/__auth/register'
import { Route as _authLoginRouteImport } from './routes/__auth/login'
import { Route as _authForgotPasswordRouteImport } from './routes/__auth/forgot-password'
import { Route as AuthenticatedIrpfIndexRouteImport } from './routes/_authenticated/irpf.index'
import { Route as AuthenticatedCarteiraIndexRouteImport } from './routes/_authenticated/carteira.index'
import { Route as AuthenticatedPortfolioPortfolioIdRouteImport } from './routes/_authenticated/portfolio.$portfolioId'
import { Route as AuthenticatedCarteiraRentabilidadeRouteImport } from './routes/_authenticated/carteira.rentabilidade'
import { Route as AuthenticatedCarteiraProventosRouteImport } from './routes/_authenticated/carteira.proventos'
import { Route as AuthenticatedCarteiraPatrimonioRouteImport } from './routes/_authenticated/carteira.patrimonio'
import { Route as AuthenticatedCarteiraOperacoesRouteImport } from './routes/_authenticated/carteira.operacoes'
import { Route as AuthenticatedCarteiraMetasRouteImport } from './routes/_authenticated/carteira.metas'
import { Route as AuthenticatedCarteiraLancamentosRouteImport } from './routes/_authenticated/carteira.lancamentos'
import { Route as AuthenticatedCarteiraIrpfRouteImport } from './routes/_authenticated/carteira.irpf'
import { Route as AuthenticatedCarteiraCoberturaRouteImport } from './routes/_authenticated/carteira.cobertura'
import { Route as AuthenticatedCarteiraAnaliseRouteImport } from './routes/_authenticated/carteira.analise'
import { Route as AuthenticatedPortfolioPortfolioIdRebalancingRouteImport } from './routes/_authenticated/portfolio.$portfolioId.rebalancing'
import { Route as AuthenticatedPortfolioPortfolioIdOperationsRouteImport } from './routes/_authenticated/portfolio.$portfolioId.operations'
import { Route as AuthenticatedPortfolioPortfolioIdHistoryRouteImport } from './routes/_authenticated/portfolio.$portfolioId.history'
import { Route as AuthenticatedPortfolioPortfolioIdDividendsRouteImport } from './routes/_authenticated/portfolio.$portfolioId.dividends'

const SetoresRoute = SetoresRouteImport.update({
  id: '/setores',
  path: '/setores',
  getParentRoute: () => rootRouteImport,
} as any)
const RankingsRoute = RankingsRouteImport.update({
  id: '/rankings',
  path: '/rankings',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasRoute = NoticiasRouteImport.update({
  id: '/noticias',
  path: '/noticias',
  getParentRoute: () => rootRouteImport,
} as any)
const FiisRoute = FiisRouteImport.update({
  id: '/fiis',
  path: '/fiis',
  getParentRoute: () => rootRouteImport,
} as any)
const DividendosRoute = DividendosRouteImport.update({
  id: '/dividendos',
  path: '/dividendos',
  getParentRoute: () => rootRouteImport,
} as any)
const CompararRoute = CompararRouteImport.update({
  id: '/comparar',
  path: '/comparar',
  getParentRoute: () => rootRouteImport,
} as any)
const CarteirasRecomendadasRoute = CarteirasRecomendadasRouteImport.update({
  id: '/carteiras-recomendadas',
  path: '/carteiras-recomendadas',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculadorasRoute = CalculadorasRouteImport.update({
  id: '/calculadoras',
  path: '/calculadoras',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistIndexRoute = WatchlistIndexRouteImport.update({
  id: '/watchlist/',
  path: '/watchlist/',
  getParentRoute: () => rootRouteImport,
} as any)
const FiiTickerRoute = FiiTickerRouteImport.update({
  id: '/fii/$ticker',
  path: '/fii/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const AtivoTickerRoute = AtivoTickerRouteImport.update({
  id: '/ativo/$ticker',
  path: '/ativo/$ticker',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedProvisionadorRoute =
  AuthenticatedProvisionadorRouteImport.update({
    id: '/provisionador',
    path: '/provisionador',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMetasRoute = AuthenticatedMetasRouteImport.update({
  id: '/metas',
  path: '/metas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteiraRoute = AuthenticatedCarteiraRouteImport.update({
  id: '/carteira',
  path: '/carteira',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const _authRegisterRoute = _authRegisterRouteImport.update({
  id: '/__auth/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const _authLoginRoute = _authLoginRouteImport.update({
  id: '/__auth/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const _authForgotPasswordRoute = _authForgotPasswordRouteImport.update({
  id: '/__auth/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIrpfIndexRoute = AuthenticatedIrpfIndexRouteImport.update({
  id: '/irpf/',
  path: '/irpf/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCarteiraIndexRoute =
  AuthenticatedCarteiraIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedPortfolioPortfolioIdRoute =
  AuthenticatedPortfolioPortfolioIdRouteImport.update({
    id: '/portfolio/$portfolioId',
    path: '/portfolio/$portfolioId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedCarteiraRentabilidadeRoute =
  AuthenticatedCarteiraRentabilidadeRouteImport.update({
    id: '/rentabilidade',
    path: '/rentabilidade',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraProventosRoute =
  AuthenticatedCarteiraProventosRouteImport.update({
    id: '/proventos',
    path: '/proventos',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraPatrimonioRoute =
  AuthenticatedCarteiraPatrimonioRouteImport.update({
    id: '/patrimonio',
    path: '/patrimonio',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraOperacoesRoute =
  AuthenticatedCarteiraOperacoesRouteImport.update({
    id: '/operacoes',
    path: '/operacoes',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraMetasRoute =
  AuthenticatedCarteiraMetasRouteImport.update({
    id: '/metas',
    path: '/metas',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraLancamentosRoute =
  AuthenticatedCarteiraLancamentosRouteImport.update({
    id: '/lancamentos',
    path: '/lancamentos',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraIrpfRoute =
  AuthenticatedCarteiraIrpfRouteImport.update({
    id: '/irpf',
    path: '/irpf',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraCoberturaRoute =
  AuthenticatedCarteiraCoberturaRouteImport.update({
    id: '/cobertura',
    path: '/cobertura',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedCarteiraAnaliseRoute =
  AuthenticatedCarteiraAnaliseRouteImport.update({
    id: '/analise',
    path: '/analise',
    getParentRoute: () => AuthenticatedCarteiraRoute,
  } as any)
const AuthenticatedPortfolioPortfolioIdRebalancingRoute =
  AuthenticatedPortfolioPortfolioIdRebalancingRouteImport.update({
    id: '/rebalancing',
    path: '/rebalancing',
    getParentRoute: () => AuthenticatedPortfolioPortfolioIdRoute,
  } as any)
const AuthenticatedPortfolioPortfolioIdOperationsRoute =
  AuthenticatedPortfolioPortfolioIdOperationsRouteImport.update({
    id: '/operations',
    path: '/operations',
    getParentRoute: () => AuthenticatedPortfolioPortfolioIdRoute,
  } as any)
const AuthenticatedPortfolioPortfolioIdHistoryRoute =
  AuthenticatedPortfolioPortfolioIdHistoryRouteImport.update({
    id: '/history',
    path: '/history',
    getParentRoute: () => AuthenticatedPortfolioPortfolioIdRoute,
  } as any)
const AuthenticatedPortfolioPortfolioIdDividendsRoute =
  AuthenticatedPortfolioPortfolioIdDividendsRouteImport.update({
    id: '/dividends',
    path: '/dividends',
    getParentRoute: () => AuthenticatedPortfolioPortfolioIdRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculadoras': typeof CalculadorasRoute
  '/carteiras-recomendadas': typeof CarteirasRecomendadasRoute
  '/comparar': typeof CompararRoute
  '/dividendos': typeof DividendosRoute
  '/fiis': typeof FiisRoute
  '/noticias': typeof NoticiasRoute
  '/rankings': typeof RankingsRoute
  '/setores': typeof SetoresRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/login': typeof _authLoginRoute
  '/register': typeof _authRegisterRoute
  '/carteira': typeof AuthenticatedCarteiraRouteWithChildren
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/provisionador': typeof AuthenticatedProvisionadorRoute
  '/ativo/$ticker': typeof AtivoTickerRoute
  '/fii/$ticker': typeof FiiTickerRoute
  '/watchlist/': typeof WatchlistIndexRoute
  '/carteira/analise': typeof AuthenticatedCarteiraAnaliseRoute
  '/carteira/cobertura': typeof AuthenticatedCarteiraCoberturaRoute
  '/carteira/irpf': typeof AuthenticatedCarteiraIrpfRoute
  '/carteira/lancamentos': typeof AuthenticatedCarteiraLancamentosRoute
  '/carteira/metas': typeof AuthenticatedCarteiraMetasRoute
  '/carteira/operacoes': typeof AuthenticatedCarteiraOperacoesRoute
  '/carteira/patrimonio': typeof AuthenticatedCarteiraPatrimonioRoute
  '/carteira/proventos': typeof AuthenticatedCarteiraProventosRoute
  '/carteira/rentabilidade': typeof AuthenticatedCarteiraRentabilidadeRoute
  '/portfolio/$portfolioId': typeof AuthenticatedPortfolioPortfolioIdRouteWithChildren
  '/carteira/': typeof AuthenticatedCarteiraIndexRoute
  '/irpf/': typeof AuthenticatedIrpfIndexRoute
  '/portfolio/$portfolioId/dividends': typeof AuthenticatedPortfolioPortfolioIdDividendsRoute
  '/portfolio/$portfolioId/history': typeof AuthenticatedPortfolioPortfolioIdHistoryRoute
  '/portfolio/$portfolioId/operations': typeof AuthenticatedPortfolioPortfolioIdOperationsRoute
  '/portfolio/$portfolioId/rebalancing': typeof AuthenticatedPortfolioPortfolioIdRebalancingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/calculadoras': typeof CalculadorasRoute
  '/carteiras-recomendadas': typeof CarteirasRecomendadasRoute
  '/comparar': typeof CompararRoute
  '/dividendos': typeof DividendosRoute
  '/fiis': typeof FiisRoute
  '/noticias': typeof NoticiasRoute
  '/rankings': typeof RankingsRoute
  '/setores': typeof SetoresRoute
  '/forgot-password': typeof _authForgotPasswordRoute
  '/login': typeof _authLoginRoute
  '/register': typeof _authRegisterRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/metas': typeof AuthenticatedMetasRoute
  '/provisionador': typeof AuthenticatedProvisionadorRoute
  '/ativo/$ticker': typeof AtivoTickerRoute
  '/fii/$ticker': typeof FiiTickerRoute
  '/watchlist': typeof WatchlistIndexRoute
  '/carteira/analise': typeof AuthenticatedCarteiraAnaliseRoute
  '/carteira/cobertura': typeof AuthenticatedCarteiraCoberturaRoute
  '/carteira/irpf': typeof AuthenticatedCarteiraIrpfRoute
  '/carteira/lancamentos': typeof AuthenticatedCarteiraLancamentosRoute
  '/carteira/metas': typeof AuthenticatedCarteiraMetasRoute
  '/carteira/operacoes': typeof AuthenticatedCarteiraOperacoesRoute
  '/carteira/patrimonio': typeof AuthenticatedCarteiraPatrimonioRoute
  '/carteira/proventos': typeof AuthenticatedCarteiraProventosRoute
  '/carteira/rentabilidade': typeof AuthenticatedCarteiraRentabilidadeRoute
  '/portfolio/$portfolioId': typeof AuthenticatedPortfolioPortfolioIdRouteWithChildren
  '/carteira': typeof AuthenticatedCarteiraIndexRoute
  '/irpf': typeof AuthenticatedIrpfIndexRoute
  '/portfolio/$portfolioId/dividends': typeof AuthenticatedPortfolioPortfolioIdDividendsRoute
  '/portfolio/$portfolioId/history': typeof AuthenticatedPortfolioPortfolioIdHistoryRoute
  '/portfolio/$portfolioId/operations': typeof AuthenticatedPortfolioPortfolioIdOperationsRoute
  '/portfolio/$portfolioId/rebalancing': typeof AuthenticatedPortfolioPortfolioIdRebalancingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/calculadoras': typeof CalculadorasRoute
  '/carteiras-recomendadas': typeof CarteirasRecomendadasRoute
  '/comparar': typeof CompararRoute
  '/dividendos': typeof DividendosRoute
  '/fiis': typeof FiisRoute
  '/noticias': typeof NoticiasRoute
  '/rankings': typeof RankingsRoute
  '/setores': typeof SetoresRoute
  '/__auth/forgot-password': typeof _authForgotPasswordRoute
  '/__auth/login': typeof _authLoginRoute
  '/__auth/register': typeof _authRegisterRoute
  '/_authenticated/carteira': typeof AuthenticatedCarteiraRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/metas': typeof AuthenticatedMetasRoute
  '/_authenticated/provisionador': typeof AuthenticatedProvisionadorRoute
  '/ativo/$ticker': typeof AtivoTickerRoute
  '/fii/$ticker': typeof FiiTickerRoute
  '/watchlist/': typeof WatchlistIndexRoute
  '/_authenticated/carteira/analise': typeof AuthenticatedCarteiraAnaliseRoute
  '/_authenticated/carteira/cobertura': typeof AuthenticatedCarteiraCoberturaRoute
  '/_authenticated/carteira/irpf': typeof AuthenticatedCarteiraIrpfRoute
  '/_authenticated/carteira/lancamentos': typeof AuthenticatedCarteiraLancamentosRoute
  '/_authenticated/carteira/metas': typeof AuthenticatedCarteiraMetasRoute
  '/_authenticated/carteira/operacoes': typeof AuthenticatedCarteiraOperacoesRoute
  '/_authenticated/carteira/patrimonio': typeof AuthenticatedCarteiraPatrimonioRoute
  '/_authenticated/carteira/proventos': typeof AuthenticatedCarteiraProventosRoute
  '/_authenticated/carteira/rentabilidade': typeof AuthenticatedCarteiraRentabilidadeRoute
  '/_authenticated/portfolio/$portfolioId': typeof AuthenticatedPortfolioPortfolioIdRouteWithChildren
  '/_authenticated/carteira/': typeof AuthenticatedCarteiraIndexRoute
  '/_authenticated/irpf/': typeof AuthenticatedIrpfIndexRoute
  '/_authenticated/portfolio/$portfolioId/dividends': typeof AuthenticatedPortfolioPortfolioIdDividendsRoute
  '/_authenticated/portfolio/$portfolioId/history': typeof AuthenticatedPortfolioPortfolioIdHistoryRoute
  '/_authenticated/portfolio/$portfolioId/operations': typeof AuthenticatedPortfolioPortfolioIdOperationsRoute
  '/_authenticated/portfolio/$portfolioId/rebalancing': typeof AuthenticatedPortfolioPortfolioIdRebalancingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/calculadoras'
    | '/carteiras-recomendadas'
    | '/comparar'
    | '/dividendos'
    | '/fiis'
    | '/noticias'
    | '/rankings'
    | '/setores'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/carteira'
    | '/dashboard'
    | '/metas'
    | '/provisionador'
    | '/ativo/$ticker'
    | '/fii/$ticker'
    | '/watchlist/'
    | '/carteira/analise'
    | '/carteira/cobertura'
    | '/carteira/irpf'
    | '/carteira/lancamentos'
    | '/carteira/metas'
    | '/carteira/operacoes'
    | '/carteira/patrimonio'
    | '/carteira/proventos'
    | '/carteira/rentabilidade'
    | '/portfolio/$portfolioId'
    | '/carteira/'
    | '/irpf/'
    | '/portfolio/$portfolioId/dividends'
    | '/portfolio/$portfolioId/history'
    | '/portfolio/$portfolioId/operations'
    | '/portfolio/$portfolioId/rebalancing'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/calculadoras'
    | '/carteiras-recomendadas'
    | '/comparar'
    | '/dividendos'
    | '/fiis'
    | '/noticias'
    | '/rankings'
    | '/setores'
    | '/forgot-password'
    | '/login'
    | '/register'
    | '/dashboard'
    | '/metas'
    | '/provisionador'
    | '/ativo/$ticker'
    | '/fii/$ticker'
    | '/watchlist'
    | '/carteira/analise'
    | '/carteira/cobertura'
    | '/carteira/irpf'
    | '/carteira/lancamentos'
    | '/carteira/metas'
    | '/carteira/operacoes'
    | '/carteira/patrimonio'
    | '/carteira/proventos'
    | '/carteira/rentabilidade'
    | '/portfolio/$portfolioId'
    | '/carteira'
    | '/irpf'
    | '/portfolio/$portfolioId/dividends'
    | '/portfolio/$portfolioId/history'
    | '/portfolio/$portfolioId/operations'
    | '/portfolio/$portfolioId/rebalancing'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/calculadoras'
    | '/carteiras-recomendadas'
    | '/comparar'
    | '/dividendos'
    | '/fiis'
    | '/noticias'
    | '/rankings'
    | '/setores'
    | '/__auth/forgot-password'
    | '/__auth/login'
    | '/__auth/register'
    | '/_authenticated/carteira'
    | '/_authenticated/dashboard'
    | '/_authenticated/metas'
    | '/_authenticated/provisionador'
    | '/ativo/$ticker'
    | '/fii/$ticker'
    | '/watchlist/'
    | '/_authenticated/carteira/analise'
    | '/_authenticated/carteira/cobertura'
    | '/_authenticated/carteira/irpf'
    | '/_authenticated/carteira/lancamentos'
    | '/_authenticated/carteira/metas'
    | '/_authenticated/carteira/operacoes'
    | '/_authenticated/carteira/patrimonio'
    | '/_authenticated/carteira/proventos'
    | '/_authenticated/carteira/rentabilidade'
    | '/_authenticated/portfolio/$portfolioId'
    | '/_authenticated/carteira/'
    | '/_authenticated/irpf/'
    | '/_authenticated/portfolio/$portfolioId/dividends'
    | '/_authenticated/portfolio/$portfolioId/history'
    | '/_authenticated/portfolio/$portfolioId/operations'
    | '/_authenticated/portfolio/$portfolioId/rebalancing'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  CalculadorasRoute: typeof CalculadorasRoute
  CarteirasRecomendadasRoute: typeof CarteirasRecomendadasRoute
  CompararRoute: typeof CompararRoute
  DividendosRoute: typeof DividendosRoute
  FiisRoute: typeof FiisRoute
  NoticiasRoute: typeof NoticiasRoute
  RankingsRoute: typeof RankingsRoute
  SetoresRoute: typeof SetoresRoute
  _authForgotPasswordRoute: typeof _authForgotPasswordRoute
  _authLoginRoute: typeof _authLoginRoute
  _authRegisterRoute: typeof _authRegisterRoute
  AtivoTickerRoute: typeof AtivoTickerRoute
  FiiTickerRoute: typeof FiiTickerRoute
  WatchlistIndexRoute: typeof WatchlistIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/setores': {
      id: '/setores'
      path: '/setores'
      fullPath: '/setores'
      preLoaderRoute: typeof SetoresRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rankings': {
      id: '/rankings'
      path: '/rankings'
      fullPath: '/rankings'
      preLoaderRoute: typeof RankingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias': {
      id: '/noticias'
      path: '/noticias'
      fullPath: '/noticias'
      preLoaderRoute: typeof NoticiasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fiis': {
      id: '/fiis'
      path: '/fiis'
      fullPath: '/fiis'
      preLoaderRoute: typeof FiisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dividendos': {
      id: '/dividendos'
      path: '/dividendos'
      fullPath: '/dividendos'
      preLoaderRoute: typeof DividendosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparar': {
      id: '/comparar'
      path: '/comparar'
      fullPath: '/comparar'
      preLoaderRoute: typeof CompararRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carteiras-recomendadas': {
      id: '/carteiras-recomendadas'
      path: '/carteiras-recomendadas'
      fullPath: '/carteiras-recomendadas'
      preLoaderRoute: typeof CarteirasRecomendadasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculadoras': {
      id: '/calculadoras'
      path: '/calculadoras'
      fullPath: '/calculadoras'
      preLoaderRoute: typeof CalculadorasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist/': {
      id: '/watchlist/'
      path: '/watchlist'
      fullPath: '/watchlist/'
      preLoaderRoute: typeof WatchlistIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fii/$ticker': {
      id: '/fii/$ticker'
      path: '/fii/$ticker'
      fullPath: '/fii/$ticker'
      preLoaderRoute: typeof FiiTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ativo/$ticker': {
      id: '/ativo/$ticker'
      path: '/ativo/$ticker'
      fullPath: '/ativo/$ticker'
      preLoaderRoute: typeof AtivoTickerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/provisionador': {
      id: '/_authenticated/provisionador'
      path: '/provisionador'
      fullPath: '/provisionador'
      preLoaderRoute: typeof AuthenticatedProvisionadorRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/metas': {
      id: '/_authenticated/metas'
      path: '/metas'
      fullPath: '/metas'
      preLoaderRoute: typeof AuthenticatedMetasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira': {
      id: '/_authenticated/carteira'
      path: '/carteira'
      fullPath: '/carteira'
      preLoaderRoute: typeof AuthenticatedCarteiraRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/__auth/register': {
      id: '/__auth/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof _authRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth/login': {
      id: '/__auth/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof _authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/__auth/forgot-password': {
      id: '/__auth/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof _authForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/irpf/': {
      id: '/_authenticated/irpf/'
      path: '/irpf'
      fullPath: '/irpf/'
      preLoaderRoute: typeof AuthenticatedIrpfIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira/': {
      id: '/_authenticated/carteira/'
      path: '/'
      fullPath: '/carteira/'
      preLoaderRoute: typeof AuthenticatedCarteiraIndexRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/portfolio/$portfolioId': {
      id: '/_authenticated/portfolio/$portfolioId'
      path: '/portfolio/$portfolioId'
      fullPath: '/portfolio/$portfolioId'
      preLoaderRoute: typeof AuthenticatedPortfolioPortfolioIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/carteira/rentabilidade': {
      id: '/_authenticated/carteira/rentabilidade'
      path: '/rentabilidade'
      fullPath: '/carteira/rentabilidade'
      preLoaderRoute: typeof AuthenticatedCarteiraRentabilidadeRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/proventos': {
      id: '/_authenticated/carteira/proventos'
      path: '/proventos'
      fullPath: '/carteira/proventos'
      preLoaderRoute: typeof AuthenticatedCarteiraProventosRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/patrimonio': {
      id: '/_authenticated/carteira/patrimonio'
      path: '/patrimonio'
      fullPath: '/carteira/patrimonio'
      preLoaderRoute: typeof AuthenticatedCarteiraPatrimonioRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/operacoes': {
      id: '/_authenticated/carteira/operacoes'
      path: '/operacoes'
      fullPath: '/carteira/operacoes'
      preLoaderRoute: typeof AuthenticatedCarteiraOperacoesRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/metas': {
      id: '/_authenticated/carteira/metas'
      path: '/metas'
      fullPath: '/carteira/metas'
      preLoaderRoute: typeof AuthenticatedCarteiraMetasRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/lancamentos': {
      id: '/_authenticated/carteira/lancamentos'
      path: '/lancamentos'
      fullPath: '/carteira/lancamentos'
      preLoaderRoute: typeof AuthenticatedCarteiraLancamentosRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/irpf': {
      id: '/_authenticated/carteira/irpf'
      path: '/irpf'
      fullPath: '/carteira/irpf'
      preLoaderRoute: typeof AuthenticatedCarteiraIrpfRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/cobertura': {
      id: '/_authenticated/carteira/cobertura'
      path: '/cobertura'
      fullPath: '/carteira/cobertura'
      preLoaderRoute: typeof AuthenticatedCarteiraCoberturaRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/carteira/analise': {
      id: '/_authenticated/carteira/analise'
      path: '/analise'
      fullPath: '/carteira/analise'
      preLoaderRoute: typeof AuthenticatedCarteiraAnaliseRouteImport
      parentRoute: typeof AuthenticatedCarteiraRoute
    }
    '/_authenticated/portfolio/$portfolioId/rebalancing': {
      id: '/_authenticated/portfolio/$portfolioId/rebalancing'
      path: '/rebalancing'
      fullPath: '/portfolio/$portfolioId/rebalancing'
      preLoaderRoute: typeof AuthenticatedPortfolioPortfolioIdRebalancingRouteImport
      parentRoute: typeof AuthenticatedPortfolioPortfolioIdRoute
    }
    '/_authenticated/portfolio/$portfolioId/operations': {
      id: '/_authenticated/portfolio/$portfolioId/operations'
      path: '/operations'
      fullPath: '/portfolio/$portfolioId/operations'
      preLoaderRoute: typeof AuthenticatedPortfolioPortfolioIdOperationsRouteImport
      parentRoute: typeof AuthenticatedPortfolioPortfolioIdRoute
    }
    '/_authenticated/portfolio/$portfolioId/history': {
      id: '/_authenticated/portfolio/$portfolioId/history'
      path: '/history'
      fullPath: '/portfolio/$portfolioId/history'
      preLoaderRoute: typeof AuthenticatedPortfolioPortfolioIdHistoryRouteImport
      parentRoute: typeof AuthenticatedPortfolioPortfolioIdRoute
    }
    '/_authenticated/portfolio/$portfolioId/dividends': {
      id: '/_authenticated/portfolio/$portfolioId/dividends'
      path: '/dividends'
      fullPath: '/portfolio/$portfolioId/dividends'
      preLoaderRoute: typeof AuthenticatedPortfolioPortfolioIdDividendsRouteImport
      parentRoute: typeof AuthenticatedPortfolioPortfolioIdRoute
    }
  }
}

interface AuthenticatedCarteiraRouteChildren {
  AuthenticatedCarteiraAnaliseRoute: typeof AuthenticatedCarteiraAnaliseRoute
  AuthenticatedCarteiraCoberturaRoute: typeof AuthenticatedCarteiraCoberturaRoute
  AuthenticatedCarteiraIrpfRoute: typeof AuthenticatedCarteiraIrpfRoute
  AuthenticatedCarteiraLancamentosRoute: typeof AuthenticatedCarteiraLancamentosRoute
  AuthenticatedCarteiraMetasRoute: typeof AuthenticatedCarteiraMetasRoute
  AuthenticatedCarteiraOperacoesRoute: typeof AuthenticatedCarteiraOperacoesRoute
  AuthenticatedCarteiraPatrimonioRoute: typeof AuthenticatedCarteiraPatrimonioRoute
  AuthenticatedCarteiraProventosRoute: typeof AuthenticatedCarteiraProventosRoute
  AuthenticatedCarteiraRentabilidadeRoute: typeof AuthenticatedCarteiraRentabilidadeRoute
  AuthenticatedCarteiraIndexRoute: typeof AuthenticatedCarteiraIndexRoute
}

const AuthenticatedCarteiraRouteChildren: AuthenticatedCarteiraRouteChildren = {
  AuthenticatedCarteiraAnaliseRoute: AuthenticatedCarteiraAnaliseRoute,
  AuthenticatedCarteiraCoberturaRoute: AuthenticatedCarteiraCoberturaRoute,
  AuthenticatedCarteiraIrpfRoute: AuthenticatedCarteiraIrpfRoute,
  AuthenticatedCarteiraLancamentosRoute: AuthenticatedCarteiraLancamentosRoute,
  AuthenticatedCarteiraMetasRoute: AuthenticatedCarteiraMetasRoute,
  AuthenticatedCarteiraOperacoesRoute: AuthenticatedCarteiraOperacoesRoute,
  AuthenticatedCarteiraPatrimonioRoute: AuthenticatedCarteiraPatrimonioRoute,
  AuthenticatedCarteiraProventosRoute: AuthenticatedCarteiraProventosRoute,
  AuthenticatedCarteiraRentabilidadeRoute:
    AuthenticatedCarteiraRentabilidadeRoute,
  AuthenticatedCarteiraIndexRoute: AuthenticatedCarteiraIndexRoute,
}

const AuthenticatedCarteiraRouteWithChildren =
  AuthenticatedCarteiraRoute._addFileChildren(
    AuthenticatedCarteiraRouteChildren,
  )

interface AuthenticatedPortfolioPortfolioIdRouteChildren {
  AuthenticatedPortfolioPortfolioIdDividendsRoute: typeof AuthenticatedPortfolioPortfolioIdDividendsRoute
  AuthenticatedPortfolioPortfolioIdHistoryRoute: typeof AuthenticatedPortfolioPortfolioIdHistoryRoute
  AuthenticatedPortfolioPortfolioIdOperationsRoute: typeof AuthenticatedPortfolioPortfolioIdOperationsRoute
  AuthenticatedPortfolioPortfolioIdRebalancingRoute: typeof AuthenticatedPortfolioPortfolioIdRebalancingRoute
}

const AuthenticatedPortfolioPortfolioIdRouteChildren: AuthenticatedPortfolioPortfolioIdRouteChildren =
  {
    AuthenticatedPortfolioPortfolioIdDividendsRoute:
      AuthenticatedPortfolioPortfolioIdDividendsRoute,
    AuthenticatedPortfolioPortfolioIdHistoryRoute:
      AuthenticatedPortfolioPortfolioIdHistoryRoute,
    AuthenticatedPortfolioPortfolioIdOperationsRoute:
      AuthenticatedPortfolioPortfolioIdOperationsRoute,
    AuthenticatedPortfolioPortfolioIdRebalancingRoute:
      AuthenticatedPortfolioPortfolioIdRebalancingRoute,
  }

const AuthenticatedPortfolioPortfolioIdRouteWithChildren =
  AuthenticatedPortfolioPortfolioIdRoute._addFileChildren(
    AuthenticatedPortfolioPortfolioIdRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCarteiraRoute: typeof AuthenticatedCarteiraRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedMetasRoute: typeof AuthenticatedMetasRoute
  AuthenticatedProvisionadorRoute: typeof AuthenticatedProvisionadorRoute
  AuthenticatedPortfolioPortfolioIdRoute: typeof AuthenticatedPortfolioPortfolioIdRouteWithChildren
  AuthenticatedIrpfIndexRoute: typeof AuthenticatedIrpfIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCarteiraRoute: AuthenticatedCarteiraRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedMetasRoute: AuthenticatedMetasRoute,
  AuthenticatedProvisionadorRoute: AuthenticatedProvisionadorRoute,
  AuthenticatedPortfolioPortfolioIdRoute:
    AuthenticatedPortfolioPortfolioIdRouteWithChildren,
  AuthenticatedIrpfIndexRoute: AuthenticatedIrpfIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  CalculadorasRoute: CalculadorasRoute,
  CarteirasRecomendadasRoute: CarteirasRecomendadasRoute,
  CompararRoute: CompararRoute,
  DividendosRoute: DividendosRoute,
  FiisRoute: FiisRoute,
  NoticiasRoute: NoticiasRoute,
  RankingsRoute: RankingsRoute,
  SetoresRoute: SetoresRoute,
  _authForgotPasswordRoute: _authForgotPasswordRoute,
  _authLoginRoute: _authLoginRoute,
  _authRegisterRoute: _authRegisterRoute,
  AtivoTickerRoute: AtivoTickerRoute,
  FiiTickerRoute: FiiTickerRoute,
  WatchlistIndexRoute: WatchlistIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
